export interface Celebrity {
  id: string;
  name: string;
  nameEn: string;
  category: string;
  tags: string[];
  referencePrompt: string; // 描述名人的外貌特征，用于prompt拼接
  avatarUrl: string; // 头像占位，MVP用emoji
  hotness: number; // 热度排序
}

export const categories = [
  { id: 'all', label: '全部', emoji: '🔥' },
  { id: 'cpop', label: '华语明星', emoji: '🎤' },
  { id: 'kpop', label: '日韩偶像', emoji: '🌸' },
  { id: 'hollywood', label: '好莱坞', emoji: '🎬' },
  { id: 'tech', label: '科技大佬', emoji: '💻' },
  { id: 'sports', label: '体育巨星', emoji: '⚽' },
  { id: 'business', label: '政商领袖', emoji: '💼' },
] as const;

export const celebrities: Celebrity[] = [
  // 华语明星
  {
    id: 'jay-chou',
    name: '周杰伦',
    nameEn: 'Jay Chou',
    category: 'cpop',
    tags: ['歌手', '华语'],
    referencePrompt: 'Jay Chou, Taiwanese singer, sharp jawline, slightly long black hair swept across forehead, charismatic smile, wearing stylish casual outfit',
    avatarUrl: '🎤',
    hotness: 100,
  },
  {
    id: 'taylor-swift',
    name: 'Taylor Swift',
    nameEn: 'Taylor Swift',
    category: 'hollywood',
    tags: ['歌手', '欧美'],
    referencePrompt: 'Taylor Swift, American singer-songwriter, tall slender figure, blonde hair, blue eyes, red lipstick, wearing a sparkly dress or elegant outfit',
    avatarUrl: '💃',
    hotness: 99,
  },
  {
    id: 'elon-musk',
    name: 'Elon Musk',
    nameEn: 'Elon Musk',
    category: 'tech',
    tags: ['科技', 'CEO'],
    referencePrompt: 'Elon Musk, CEO of Tesla and SpaceX, medium build, short light brown hair, distinctive jawline, often wearing a dark t-shirt or suit, confident expression',
    avatarUrl: '🚀',
    hotness: 98,
  },
  {
    id: 'leo-messi',
    name: 'Messi',
    nameEn: 'Lionel Messi',
    category: 'sports',
    tags: ['足球', '阿根廷'],
    referencePrompt: 'Lionel Messi, Argentine footballer, relatively short stature, beard, short dark hair, athletic build, wearing Argentina national team jersey or casual sportswear',
    avatarUrl: '⚽',
    hotness: 97,
  },
  {
    id: 'jackie-chan',
    name: '成龙',
    nameEn: 'Jackie Chan',
    category: 'cpop',
    tags: ['演员', '功夫'],
    referencePrompt: 'Jackie Chan, Hong Kong actor and martial artist, medium build, distinctive messy black hair, warm smile, wearing casual or action-style outfit',
    avatarUrl: '🥋',
    hotness: 96,
  },
  {
    id: 'kim-taehyung',
    name: '金泰亨 (V)',
    nameEn: 'V (BTS)',
    category: 'kpop',
    tags: ['BTS', '韩流'],
    referencePrompt: 'Kim Taehyung (V) from BTS, Korean singer, handsome face with sharp features, dark hair often styled, deep voice expression, wearing fashionable Korean streetwear',
    avatarUrl: '🌸',
    hotness: 95,
  },
  {
    id: 'bianca-brandolini-dadda',
    name: '迪丽热巴',
    nameEn: 'Dilraba Dilmurat',
    category: 'cpop',
    tags: ['演员', '新疆'],
    referencePrompt: 'Dilraba (Dilireba), Chinese actress of Uyghur heritage, strikingly beautiful with large expressive eyes, high nose bridge, long black hair, elegant and glamorous appearance',
    avatarUrl: '✨',
    hotness: 94,
  },
  {
    id: 'mark-zuckerberg',
    name: '扎克伯格',
    nameEn: 'Mark Zuckerberg',
    category: 'tech',
    tags: ['科技', 'Meta'],
    referencePrompt: 'Mark Zuckerberg, CEO of Meta, short curly brown/blond hair, blue eyes, clean-shaven, often wearing a simple t-shirt or hoodie, youthful appearance',
    avatarUrl: '👤',
    hotness: 93,
  },
  {
    id: 'cristiano-ronaldo',
    name: 'C罗',
    nameEn: 'Cristiano Ronaldo',
    category: 'sports',
    tags: ['足球', '葡萄牙'],
    referencePrompt: 'Cristiano Ronaldo, Portuguese footballer, muscular athletic build, styled dark hair often gelled up, clean-shaven or light stubble, confident intense expression, wearing football jersey or tailored suit',
    avatarUrl: '🏆',
    hotness: 97,
  },
  {
    id: 'jensen-huang',
    name: '黄仁勋',
    nameEn: 'Jensen Huang',
    category: 'tech',
    tags: ['科技', 'NVIDIA'],
    referencePrompt: 'Jensen Huang, CEO of NVIDIA, distinctive silver/black hair, leather jacket (his signature look), black t-shirt underneath, glasses, warm smile, medium build',
    avatarUrl: '🎮',
    hotness: 96,
  },
  {
    id: 'billie-eilish',
    name: 'Billie Eilish',
    nameEn: 'Billie Eilish',
    category: 'hollywood',
    tags: ['歌手', '欧美'],
    referencePrompt: 'Billie Eilish, American singer, distinctive style with oversized clothing, black or neon-colored hair, piercing blue eyes, edgy and cool appearance',
    avatarUrl: '🖤',
    hotness: 92,
  },
  {
    id: 'lei-jun',
    name: '雷军',
    nameEn: 'Lei Jun',
    category: 'tech',
    tags: ['科技', '小米'],
    referencePrompt: 'Lei Jun, CEO of Xiaomi, medium build, short black hair, glasses, warm and approachable smile, wearing casual business attire or Xiaomi product launch outfit',
    avatarUrl: '📱',
    hotness: 91,
  },
  {
    id: 'iu',
    name: 'IU (李知恩)',
    nameEn: 'IU',
    category: 'kpop',
    tags: ['歌手', '韩流'],
    referencePrompt: 'IU (Lee Ji-eun), Korean singer and actress, sweet and innocent face, long straight black or brown hair, petite figure, wearing elegant feminine outfit',
    avatarUrl: '🎀',
    hotness: 93,
  },
  {
    id: 'brad-pitt',
    name: 'Brad Pitt',
    nameEn: 'Brad Pitt',
    category: 'hollywood',
    tags: ['演员', '好莱坞'],
    referencePrompt: 'Brad Pitt, American actor, handsome chiseled face, blonde hair, blue eyes, athletic build, effortlessly cool style, wearing sunglasses and casual elegant outfit',
    avatarUrl: '😎',
    hotness: 90,
  },
  {
    id: 'kobe-bryant',
    name: '科比',
    nameEn: 'Kobe Bryant',
    category: 'sports',
    tags: ['篮球', '湖人'],
    referencePrompt: 'Kobe Bryant, NBA legend, tall athletic build, bald head, intense focused expression, wearing Los Angeles Lakers jersey #24, basketball in hand',
    avatarUrl: '🏀',
    hotness: 95,
  },
  {
    id: 'blackpink-lisa',
    name: 'Lisa (BLACKPINK)',
    nameEn: 'Lisa (BLACKPINK)',
    category: 'kpop',
    tags: ['BLACKPINK', '韩流'],
    referencePrompt: 'Lisa from BLACKPINK, Thai-Korean pop star, striking features, often with bangs and long hair, incredibly stylish, wearing high-fashion K-pop stage outfit',
    avatarUrl: '💜',
    hotness: 94,
  },
  {
    id: 'trump',
    name: 'Trump',
    nameEn: 'Donald Trump',
    category: 'business',
    tags: ['政治', '美国'],
    referencePrompt: 'Donald Trump, distinctive blonde swept-back hair, squinting expression, wearing a dark navy suit with long red tie, confident posture, American flag pin on lapel',
    avatarUrl: '🇺🇸',
    hotness: 88,
  },
  {
    id: 'yi-yang-qian-xi',
    name: '易烊千玺',
    nameEn: 'Jackson Yee',
    category: 'cpop',
    tags: ['演员', 'TFBOYS'],
    referencePrompt: 'Jackson Yee (Yi Yangqianxi), Chinese actor and singer, youthful handsome face, clean-cut short black hair, expressive eyes, wearing trendy Chinese fashion',
    avatarUrl: '🌟',
    hotness: 89,
  },
  {
    id: 'sundar-pichai',
    name: '桑达尔·皮查伊',
    nameEn: 'Sundar Pichai',
    category: 'tech',
    tags: ['科技', 'Google'],
    referencePrompt: 'Sundar Pichai, CEO of Google, Indian-American, short black hair, glasses, clean-shaven, warm professional smile, wearing a casual button-down shirt',
    avatarUrl: '🔍',
    hotness: 85,
  },
  {
    id: 'rihanna',
    name: 'Rihanna',
    nameEn: 'Rihanna',
    category: 'hollywood',
    tags: ['歌手', '欧美'],
    referencePrompt: 'Rihanna, Barbadian singer and entrepreneur, stunning features, often changing hairstyles, confident glamorous look, wearing high-fashion outfit, Fenty Beauty style',
    avatarUrl: '💎',
    hotness: 91,
  },
];

export const scenarios = [
  { id: 'red-carpet', label: '走红毯', emoji: '🏆', prompt: 'walking together on a glamorous red carpet event, paparazzi cameras flashing in background' },
  { id: 'coffee', label: '一起喝咖啡', emoji: '☕', prompt: 'sitting together at a cozy cafe, having coffee and a friendly conversation, warm lighting' },
  { id: 'selfie', label: '自拍合影', emoji: '🤳', prompt: 'taking a fun selfie together, both making a peace sign or smiling at camera, close-up shot, casual fun vibe' },
  { id: 'travel', label: '旅游打卡', emoji: '✈️', prompt: 'standing together at a famous tourist landmark, traveling together, scenic background' },
  { id: 'dinner', label: '共进晚餐', emoji: '🍽️', prompt: 'having dinner together at an elegant restaurant, candlelight, fine dining atmosphere' },
  { id: 'stage', label: '同台演出', emoji: '🎤', prompt: 'performing together on a massive concert stage, dramatic stage lighting, crowd cheering in background' },
  { id: 'sports', label: '一起运动', emoji: '💪', prompt: 'playing sports together on a professional field/court, athletic atmosphere, action shot' },
  { id: 'business', label: '商务会面', emoji: '🤝', prompt: 'shaking hands at a formal business meeting, modern office or conference room, professional atmosphere' },
];
