export interface Celebrity {
  id: string;
  name: string;
  nameEn: string;
  category: string;
  tags: string[];
  referencePrompt: string; // 描述名人的外貌特征，用于prompt拼接
  avatarUrl: string; // 头像占位，MVP用emoji
  hotness: number; // 热度排序
}

export const categories = [
  { id: 'all', label: '全部', emoji: '🔥' },
  { id: 'kpop', label: '日韩偶像', emoji: '🌸' },
  { id: 'hollywood', label: '好莱坞', emoji: '🎬' },
  { id: 'music', label: '音乐巨星', emoji: '🎵' },
  { id: 'tech', label: '科技大佬', emoji: '💻' },
  { id: 'sports', label: '体育巨星', emoji: '⚽' },
  { id: 'anime', label: '动漫角色', emoji: '⚡' },
  { id: 'business', label: '政商领袖', emoji: '💼' },
] as const;

export const celebrities: Celebrity[] = [
  // ========== 日韩偶像 ==========
  {
    id: 'kim-taehyung',
    name: '金泰亨 (V)',
    nameEn: 'V (BTS)',
    category: 'kpop',
    tags: ['BTS', '韩流'],
    referencePrompt: 'a member of the world-famous K-pop boy group BTS, the one known as V — young Korean man with deep handsome face, sharp jawline, slightly wavy dark brown hair parted in the middle, mesmerizing eyes, tall lean build, wearing trendy Korean streetwear',
    avatarUrl: '🌸',
    hotness: 95,
  },
  {
    id: 'blackpink-lisa',
    name: 'Lisa (莉莎·BLACKPINK)',
    nameEn: 'Lisa (BLACKPINK)',
    category: 'kpop',
    tags: ['BLACKPINK', '韩流'],
    referencePrompt: 'the Thai-born main dancer of the K-pop girl group BLACKPINK, Lisa — young Southeast Asian woman with cat-like eyes, long straight black hair often with bangs, slim toned figure, incredibly charismatic stage presence, wearing stylish high-fashion K-pop outfit',
    avatarUrl: '💜',
    hotness: 94,
  },
  {
    id: 'iu',
    name: 'IU (李知恩)',
    nameEn: 'IU',
    category: 'kpop',
    tags: ['歌手', '韩流'],
    referencePrompt: 'the famous Korean singer-songwriter known as IU — young Korean woman with sweet round face, large expressive eyes, long straight dark hair, petite figure, elegant feminine style, wearing a flowing dress or chic casual outfit',
    avatarUrl: '🎀',
    hotness: 93,
  },
  {
    id: 'jungkook',
    name: '田柾国',
    nameEn: 'Jungkook (BTS)',
    category: 'kpop',
    tags: ['BTS', '韩流'],
    referencePrompt: 'the youngest member and main vocalist of BTS, Jeon Jungkook — young Korean man with boyish handsome face, muscular athletic build, dark hair often styled slightly messy, doe eyes, wearing trendy streetwear or casual cool outfit',
    avatarUrl: '🐰',
    hotness: 94,
  },
  {
    id: 'jisoo',
    name: 'Jisoo (智秀·BLACKPINK)',
    nameEn: 'Jisoo (BLACKPINK)',
    category: 'kpop',
    tags: ['BLACKPINK', '韩流'],
    referencePrompt: 'the visual and lead vocalist of BLACKPINK, Kim Jisoo — young Korean woman with classic doll-like beauty, dark hair with bangs, porcelain skin, elegant refined features, wearing sophisticated high-fashion outfit',
    avatarUrl: '🌺',
    hotness: 92,
  },
  {
    id: 'sana',
    name: 'Sana (凑崎纱夏·TWICE)',
    nameEn: 'Sana (TWICE)',
    category: 'kpop',
    tags: ['TWICE', '韩流'],
    referencePrompt: 'a Japanese member of the K-pop girl group TWICE, Minatozaki Sana — young Japanese woman with adorable round face, bright eyes, long dark hair, sweet bubbly smile, wearing colorful cute K-pop stage outfit',
    avatarUrl: '🍬',
    hotness: 88,
  },

  // ========== 好莱坞 ==========
  {
    id: 'taylor-swift',
    name: 'Taylor Swift (泰勒·斯威夫特)',
    nameEn: 'Taylor Swift',
    category: 'hollywood',
    tags: ['歌手', '欧美'],
    referencePrompt: 'the world-famous pop superstar Taylor Swift — tall slender woman with signature blonde wavy hair, piercing blue eyes, sharp jawline, bold red lipstick, wearing a sparkly sequin dress or elegant outfit, confident glamorous presence',
    avatarUrl: '💃',
    hotness: 99,
  },
  {
    id: 'brad-pitt',
    name: 'Brad Pitt (布拉德·皮特)',
    nameEn: 'Brad Pitt',
    category: 'hollywood',
    tags: ['演员', '好莱坞'],
    referencePrompt: 'the legendary Hollywood actor Brad Pitt — man with strikingly handsome chiseled face, dirty blonde hair, piercing blue eyes, athletic build, effortlessly cool charismatic style, wearing sunglasses and a relaxed elegant outfit',
    avatarUrl: '😎',
    hotness: 90,
  },
  {
    id: 'rihanna',
    name: 'Rihanna (蕾哈娜)',
    nameEn: 'Rihanna',
    category: 'hollywood',
    tags: ['歌手', '欧美'],
    referencePrompt: 'the global pop icon and billionaire beauty mogul from Barbados — stunning woman with captivating features, often with bold fashion-forward hairstyles, warm brown skin, confident glamorous aura, wearing cutting-edge high-fashion outfit',
    avatarUrl: '💎',
    hotness: 91,
  },
  {
    id: 'billie-eilish',
    name: 'Billie Eilish (比莉·艾利什)',
    nameEn: 'Billie Eilish',
    category: 'hollywood',
    tags: ['歌手', '欧美'],
    referencePrompt: 'the Grammy-winning pop star Billie Eilish — young woman with distinctive edgy style, often with black or neon green hair, oversized baggy clothing, piercing striking blue-green eyes, bold unique fashion sense',
    avatarUrl: '🖤',
    hotness: 92,
  },
  {
    id: 'tom-cruise',
    name: 'Tom Cruise (汤姆·克鲁斯)',
    nameEn: 'Tom Cruise',
    category: 'hollywood',
    tags: ['演员', '好莱坞'],
    referencePrompt: 'the iconic Hollywood action star Tom Cruise — man with classically handsome face, short dark brown hair, intense magnetic blue eyes, athletic compact build, famous million-dollar smile, wearing a leather jacket or aviator sunglasses',
    avatarUrl: '🛩️',
    hotness: 89,
  },
  {
    id: 'ryan-gosling',
    name: 'Ryan Gosling (瑞恩·高斯林)',
    nameEn: 'Ryan Gosling',
    category: 'hollywood',
    tags: ['演员', '好莱坞'],
    referencePrompt: 'the Hollywood leading man Ryan Gosling — man with handsome clean-cut features, light brown hair, deep blue eyes, strong jawline, wearing a sharp tailored suit or casual stylish outfit, charming charismatic smile',
    avatarUrl: '🎭',
    hotness: 90,
  },
  {
    id: 'zendaya',
    name: 'Zendaya (赞达亚)',
    nameEn: 'Zendaya',
    category: 'hollywood',
    tags: ['演员', '好莱坞'],
    referencePrompt: 'the Hollywood actress and fashion icon Zendaya — stunning young woman with flawless features, warm brown skin, often with bold stylish hairstyles, incredibly fashionable red-carpet presence, wearing designer haute couture outfit',
    avatarUrl: '✨',
    hotness: 93,
  },
  {
    id: 'margot-robbie',
    name: 'Margot Robbie (玛格特·罗比)',
    nameEn: 'Margot Robbie',
    category: 'hollywood',
    tags: ['演员', '好莱坞'],
    referencePrompt: 'the Australian Hollywood actress Margot Robbie — beautiful woman with golden blonde hair, bright blue eyes, radiant sun-kissed complexion, dazzling confident smile, wearing a glamorous outfit',
    avatarUrl: '🦋',
    hotness: 91,
  },

  // ========== 音乐巨星 ==========
  {
    id: 'beyonce',
    name: 'Beyoncé (碧昂丝)',
    nameEn: 'Beyoncé',
    category: 'music',
    tags: ['歌手', '欧美'],
    referencePrompt: 'the legendary queen of pop and R&B Beyoncé — stunning woman with voluminous honey-blonde hair, glowing brown skin, powerful regal presence, extraordinary vocal confidence, wearing a dazzling stage performance outfit',
    avatarUrl: '👑',
    hotness: 97,
  },
  {
    id: 'drake',
    name: 'Drake (德雷克)',
    nameEn: 'Drake',
    category: 'music',
    tags: ['说唱', '欧美'],
    referencePrompt: 'the Canadian rap superstar Drake — man with full beard, short faded dark hair, medium athletic build, wearing designer streetwear or OVO hoodie, confident relaxed expression with a slight smirk',
    avatarUrl: '🦉',
    hotness: 88,
  },
  {
    id: 'eminem',
    name: 'Eminem (埃米纳姆)',
    nameEn: 'Eminem',
    category: 'music',
    tags: ['说唱', '欧美'],
    referencePrompt: 'the legendary rapper Eminem — man with short bleached blonde buzzcut hair, piercing blue eyes, slim build, intense fierce expression, wearing a hoodie or plain tank top, raw edgy Detroit energy',
    avatarUrl: '🎤',
    hotness: 86,
  },
  {
    id: 'dua-lipa',
    name: 'Dua Lipa (杜阿·利帕)',
    nameEn: 'Dua Lipa',
    category: 'music',
    tags: ['歌手', '欧美'],
    referencePrompt: 'the British-Albanian pop star Dua Lipa — beautiful woman with long dark brown hair, striking features, glamorous makeup, tall slim figure, wearing a stylish fashion-forward outfit, confident dance-pop energy',
    avatarUrl: '💃',
    hotness: 89,
  },

  // ========== 科技大佬 ==========
  {
    id: 'elon-musk',
    name: 'Elon Musk (埃隆·马斯克)',
    nameEn: 'Elon Musk',
    category: 'tech',
    tags: ['科技', 'CEO'],
    referencePrompt: 'the CEO of Tesla and SpaceX — tall man in his early 50s with short light brown hair receding at temples, angular facial structure, intense focused gaze, slim build, wearing a black t-shirt or dark suit, the world\'s most famous tech billionaire',
    avatarUrl: '🚀',
    hotness: 98,
  },
  {
    id: 'mark-zuckerberg',
    name: '扎克伯格',
    nameEn: 'Mark Zuckerberg',
    category: 'tech',
    tags: ['科技', 'Meta'],
    referencePrompt: 'the CEO of Meta (formerly Facebook) — man in his late 30s with short bleached blond curly hair, square jaw, blue eyes, slight stubble beard, medium build, wearing a plain dark t-shirt or gray hoodie, the famous social media tech billionaire',
    avatarUrl: '👤',
    hotness: 93,
  },
  {
    id: 'sundar-pichai',
    name: '桑达尔·皮查伊',
    nameEn: 'Sundar Pichai',
    category: 'tech',
    tags: ['科技', 'Google'],
    referencePrompt: 'the CEO of Google and Alphabet — Indian-American man in his early 50s with short black hair going gray at temples, round face, signature wire-frame glasses, clean-shaven, warm professional demeanor, wearing a button-down shirt or suit',
    avatarUrl: '🔍',
    hotness: 85,
  },
  {
    id: 'sam-altman',
    name: 'Sam Altman (山姆·奥特曼)',
    nameEn: 'Sam Altman',
    category: 'tech',
    tags: ['科技', 'OpenAI'],
    referencePrompt: 'the CEO of OpenAI — man in his late 30s with short brown wavy hair, clean-shaven round face, friendly intelligent eyes, slim build, wearing a brown or gray t-shirt, the famous AI tech entrepreneur',
    avatarUrl: '🤖',
    hotness: 92,
  },

  // ========== 体育巨星 ==========
  {
    id: 'leo-messi',
    name: 'Messi (梅西)',
    nameEn: 'Lionel Messi',
    category: 'sports',
    tags: ['足球', '阿根廷'],
    referencePrompt: 'the football legend Lionel Messi, 8-time Ballon d\'Or winner — relatively short man with a full beard, short dark brown hair, athletic compact build, wearing an Argentina blue and white striped jersey or Inter Miami pink jersey, magical left-footed dribbler',
    avatarUrl: '⚽',
    hotness: 97,
  },
  {
    id: 'cristiano-ronaldo',
    name: 'C罗',
    nameEn: 'Cristiano Ronaldo',
    category: 'sports',
    tags: ['足球', '葡萄牙'],
    referencePrompt: 'the football legend Cristiano Ronaldo, 5-time Ballon d\'Or winner — tall man with muscular sculpted physique, sharp jawline, styled dark hair gelled back, clean-shaven, intense competitive expression, wearing a Portugal jersey or Al Nassr shirt',
    avatarUrl: '🏆',
    hotness: 97,
  },
  {
    id: 'kobe-bryant',
    name: '科比',
    nameEn: 'Kobe Bryant',
    category: 'sports',
    tags: ['篮球', '湖人'],
    referencePrompt: 'the late Lakers legend Kobe Bryant — tall athletic man with bald head, intense focused killer gaze, muscular build, wearing a purple and gold Los Angeles Lakers jersey with number 24, the Black Mamba mentality',
    avatarUrl: '🏀',
    hotness: 95,
  },
  {
    id: 'lebron-james',
    name: 'LeBron James (勒布朗·詹姆斯)',
    nameEn: 'LeBron James',
    category: 'sports',
    tags: ['篮球', 'NBA'],
    referencePrompt: 'the NBA superstar LeBron James, often called King James — tall powerful athletic man with bald head, muscular imposing build, wearing a basketball jersey, intense confident dominant expression, the chosen one',
    avatarUrl: '👑',
    hotness: 93,
  },
  {
    id: 'michael-jordan',
    name: 'Michael Jordan (迈克尔·乔丹)',
    nameEn: 'Michael Jordan',
    category: 'sports',
    tags: ['篮球', 'NBA'],
    referencePrompt: 'the basketball GOAT Michael Jordan — tall athletic man with bald head, distinctive small goatee beard, piercing competitive eyes, wearing a red Chicago Bulls jersey with number 23, the greatest of all time aura',
    avatarUrl: '🐐',
    hotness: 96,
  },

  // ========== 动漫/虚拟角色 ==========
  {
    id: 'spider-man',
    name: 'Spider-Man (蜘蛛侠)',
    nameEn: 'Spider-Man',
    category: 'anime',
    tags: ['漫威', '超级英雄'],
    referencePrompt: 'the Marvel superhero Spider-Man in full red and blue spandex suit with intricate web pattern, white triangular eye lenses on mask, athletic agile build, dynamic web-slinging pose',
    avatarUrl: '🕷️',
    hotness: 96,
  },
  {
    id: 'iron-man',
    name: 'Iron Man (钢铁侠)',
    nameEn: 'Iron Man',
    category: 'anime',
    tags: ['漫威', '超级英雄'],
    referencePrompt: 'the Marvel superhero Iron Man in full red and gold metallic armor suit, glowing blue arc reactor in chest plate, sleek futuristic helmet with glowing eyes, powerful heroic stance',
    avatarUrl: '⚙️',
    hotness: 95,
  },
  {
    id: 'batman',
    name: 'Batman (蝙蝠侠)',
    nameEn: 'Batman',
    category: 'anime',
    tags: ['DC', '超级英雄'],
    referencePrompt: 'the DC superhero Batman in full black armored suit with dark cape and cowl, iconic bat symbol on chest, white glowing eyes on the mask, muscular build, dark brooding mysterious presence',
    avatarUrl: '🦇',
    hotness: 93,
  },
  {
    id: 'goku',
    name: '孙悟空',
    nameEn: 'Goku (Dragon Ball)',
    category: 'anime',
    tags: ['动漫', '日漫'],
    referencePrompt: 'the legendary Saiyan warrior Goku from Dragon Ball anime — spiky black hair pointing upward, wearing orange and blue martial arts gi, muscular athletic build, cheerful energetic expression with determined eyes, anime art style',
    avatarUrl: '🐉',
    hotness: 94,
  },
  {
    id: 'naruto',
    name: '鸣人',
    nameEn: 'Naruto Uzumaki',
    category: 'anime',
    tags: ['动漫', '日漫'],
    referencePrompt: 'the ninja hero Naruto Uzumaki from the Naruto anime — young man with spiky bright blonde hair, blue eyes, three whisker marks on each cheek, wearing orange and black ninja outfit with forehead protector headband, energetic bright smile, anime art style',
    avatarUrl: '🍥',
    hotness: 92,
  },
  {
    id: 'superman',
    name: 'Superman (超人)',
    nameEn: 'Superman',
    category: 'anime',
    tags: ['DC', '超级英雄'],
    referencePrompt: 'the DC superhero Superman in classic blue suit with red cape, iconic yellow S-shield symbol on chest, red boots, tall muscular heroic build, standing powerfully with cape flowing, the Man of Steel',
    avatarUrl: '🦸',
    hotness: 91,
  },
  {
    id: 'pikachu',
    name: 'Pikachu (皮卡丘)',
    nameEn: 'Pikachu (Pokémon)',
    category: 'anime',
    tags: ['动漫', '宝可梦'],
    referencePrompt: 'the iconic Pokémon Pikachu — small cute yellow mouse-like creature with pointy ears with black tips, round red cheeks, small mouth, lightning bolt shaped tail, adorable cheerful expression, cartoon anime style',
    avatarUrl: '⚡',
    hotness: 90,
  },
  {
    id: 'deadpool',
    name: 'Deadpool (死侍)',
    nameEn: 'Deadpool',
    category: 'anime',
    tags: ['漫威', '反英雄'],
    referencePrompt: 'the Marvel antihero Deadpool in full red and black tactical suit, white oval eye patches on mask, dual katana swords strapped to back, lean athletic build, playful irreverent pose with hands on hips',
    avatarUrl: '💀',
    hotness: 93,
  },

  // ========== 政商领袖 ==========
  {
    id: 'trump',
    name: 'Trump (特朗普)',
    nameEn: 'Donald Trump',
    category: 'business',
    tags: ['政治', '美国'],
    referencePrompt: 'the 45th and 47th US President Donald Trump — man with distinctive long blonde swept-back hair, squinting expression, ruddy complexion, wearing a dark navy suit with a long red tie, confident imposing posture, American flag pin on lapel',
    avatarUrl: '🇺🇸',
    hotness: 88,
  },
  {
    id: 'obama',
    name: 'Obama (奥巴马)',
    nameEn: 'Barack Obama',
    category: 'business',
    tags: ['政治', '美国'],
    referencePrompt: 'the 44th US President Barack Obama — tall man with short graying black hair, warm brown skin, signature warm intelligent smile, wearing a sharp dark suit with tie, distinguished approachable presidential presence',
    avatarUrl: '🇺🇸',
    hotness: 87,
  },
  {
    id: 'kim-jong-un',
    name: '金正恩',
    nameEn: 'Kim Jong-un',
    category: 'business',
    tags: ['政治', '朝鲜'],
    referencePrompt: 'the Supreme Leader of North Korea — heavyset East Asian man with distinctive flat-top short black pompadour haircut, clean-shaven round face, wearing a dark Mao-style button-up suit, authoritative expression',
    avatarUrl: '🇰🇵',
    hotness: 86,
  },
];

export const scenarios = [
  { id: 'red-carpet', label: '走红毯', emoji: '🏆', prompt: 'walking together on a glamorous red carpet event, paparazzi cameras flashing in background' },
  { id: 'coffee', label: '一起喝咖啡', emoji: '☕', prompt: 'sitting together at a cozy cafe, having coffee and a friendly conversation, warm lighting' },
  { id: 'selfie', label: '自拍合影', emoji: '🤳', prompt: 'taking a fun selfie together, both making a peace sign or smiling at camera, close-up shot, casual fun vibe' },
  { id: 'travel', label: '旅游打卡', emoji: '✈️', prompt: 'standing together at a famous tourist landmark, traveling together, scenic background' },
  { id: 'dinner', label: '共进晚餐', emoji: '🍽️', prompt: 'having dinner together at an elegant restaurant, candlelight, fine dining atmosphere' },
  { id: 'stage', label: '同台演出', emoji: '🎤', prompt: 'performing together on a massive concert stage, dramatic stage lighting, crowd cheering in background' },
  { id: 'sports', label: '一起运动', emoji: '💪', prompt: 'playing sports together on a professional field/court, athletic atmosphere, action shot' },
  { id: 'business', label: '商务会面', emoji: '🤝', prompt: 'shaking hands at a formal business meeting, modern office or conference room, professional atmosphere' },
  { id: 'cruise', label: '豪华邮轮', emoji: '🚢', prompt: 'standing together on the deck of a luxury cruise ship, ocean waves in background, sunset golden hour, glamorous vacation vibe' },
  { id: 'beach', label: '沙滩度假', emoji: '🏖️', prompt: 'relaxing together on a beautiful tropical beach, white sand, turquoise water, palm trees, sunny paradise atmosphere' },
  { id: 'karaoke', label: '一起K歌', emoji: '🎤', prompt: 'singing karaoke together in a private KTV room, colorful neon lights, microphones in hand, fun party atmosphere' },
  { id: 'hotpot', label: '一起吃火锅', emoji: '🍲', prompt: 'sitting together around a bubbling hotpot in a lively Chinese restaurant, steam rising, chopsticks ready, cozy dining atmosphere' },
  { id: 'studio', label: '录制播客', emoji: '🎙️', prompt: 'sitting together in a professional podcast studio with microphones and headphones, intimate conversation atmosphere, recording in progress' },
  { id: 'game', label: '一起打游戏', emoji: '🎮', prompt: 'sitting together on a couch playing video games, controllers in hand, TV screen glowing, fun competitive gaming atmosphere' },
  { id: 'graduation', label: '毕业典礼', emoji: '🎓', prompt: 'standing together at a university graduation ceremony, wearing graduation caps and gowns, throwing caps in the air, celebratory atmosphere' },
  { id: 'hospitality', label: '深夜食堂', emoji: '🌙', prompt: 'sitting together at a small late-night Japanese ramen shop counter, warm ambient lighting, steam from bowls, intimate late-night conversation' },
];
