export interface Celebrity {
  id: string;
  name: string;
  nameEn: string;
  category: string;
  tags: string[];
  referencePrompt: string; // 描述名人的外貌特征，用于prompt拼接
  avatarUrl: string; // 头像占位，MVP用emoji
  hotness: number; // 热度排序
}

export const categories = [
  { id: 'all', label: '全部', emoji: '🔥' },
  { id: 'kpop', label: '日韩偶像', emoji: '🌸' },
  { id: 'hollywood', label: '好莱坞', emoji: '🎬' },
  { id: 'music', label: '音乐巨星', emoji: '🎵' },
  { id: 'tech', label: '科技大佬', emoji: '💻' },
  { id: 'sports', label: '体育巨星', emoji: '⚽' },
  { id: 'anime', label: '动漫角色', emoji: '⚡' },
  { id: 'business', label: '政商领袖', emoji: '💼' },
] as const;

export const celebrities: Celebrity[] = [
  // ========== 日韩偶像 ==========
  {
    id: 'kim-taehyung',
    name: '金泰亨 (V)',
    nameEn: 'V (BTS)',
    category: 'kpop',
    tags: ['BTS', '韩流'],
    referencePrompt: 'A young Korean man with handsome face, sharp features, dark hair often styled, wearing fashionable Korean streetwear',
    avatarUrl: '🌸',
    hotness: 95,
  },
  {
    id: 'blackpink-lisa',
    name: 'Lisa (莉莎·BLACKPINK)',
    nameEn: 'Lisa (BLACKPINK)',
    category: 'kpop',
    tags: ['BLACKPINK', '韩流'],
    referencePrompt: 'A young Southeast Asian woman with striking features, bangs and long hair, incredibly stylish, wearing high-fashion K-pop stage outfit',
    avatarUrl: '💜',
    hotness: 94,
  },
  {
    id: 'iu',
    name: 'IU (李知恩)',
    nameEn: 'IU',
    category: 'kpop',
    tags: ['歌手', '韩流'],
    referencePrompt: 'A young Korean woman with sweet and innocent face, long straight black or brown hair, petite figure, wearing elegant feminine outfit',
    avatarUrl: '🎀',
    hotness: 93,
  },
  {
    id: 'jungkook',
    name: '田柾国',
    nameEn: 'Jungkook (BTS)',
    category: 'kpop',
    tags: ['BTS', '韩流'],
    referencePrompt: 'A young Korean man with boyish handsome face, dark hair, athletic build, wearing trendy casual streetwear, charismatic smile',
    avatarUrl: '🐰',
    hotness: 94,
  },
  {
    id: 'jisoo',
    name: 'Jisoo (智秀·BLACKPINK)',
    nameEn: 'Jisoo (BLACKPINK)',
    category: 'kpop',
    tags: ['BLACKPINK', '韩流'],
    referencePrompt: 'A young Korean woman with classic beauty, dark hair with bangs, elegant and feminine, wearing high-fashion outfit',
    avatarUrl: '🌺',
    hotness: 92,
  },
  {
    id: 'sana',
    name: 'Sana (凑崎纱夏·TWICE)',
    nameEn: 'Sana (TWICE)',
    category: 'kpop',
    tags: ['TWICE', '韩流'],
    referencePrompt: 'A young Japanese-Korean woman with adorable features, long dark hair, bright smile, wearing cute colorful K-pop outfit',
    avatarUrl: '🍬',
    hotness: 88,
  },

  // ========== 好莱坞 ==========
  {
    id: 'taylor-swift',
    name: 'Taylor Swift (泰勒·斯威夫特)',
    nameEn: 'Taylor Swift',
    category: 'hollywood',
    tags: ['歌手', '欧美'],
    referencePrompt: 'A tall slender woman with blonde hair, blue eyes, red lipstick, wearing a sparkly dress or elegant outfit',
    avatarUrl: '💃',
    hotness: 99,
  },
  {
    id: 'brad-pitt',
    name: 'Brad Pitt (布拉德·皮特)',
    nameEn: 'Brad Pitt',
    category: 'hollywood',
    tags: ['演员', '好莱坞'],
    referencePrompt: 'A man with handsome chiseled face, blonde hair, blue eyes, athletic build, effortlessly cool style, wearing sunglasses and casual elegant outfit',
    avatarUrl: '😎',
    hotness: 90,
  },
  {
    id: 'rihanna',
    name: 'Rihanna (蕾哈娜)',
    nameEn: 'Rihanna',
    category: 'hollywood',
    tags: ['歌手', '欧美'],
    referencePrompt: 'A woman with stunning features, often changing hairstyles, confident glamorous look, wearing high-fashion outfit, Caribbean heritage',
    avatarUrl: '💎',
    hotness: 91,
  },
  {
    id: 'billie-eilish',
    name: 'Billie Eilish (比莉·艾利什)',
    nameEn: 'Billie Eilish',
    category: 'hollywood',
    tags: ['歌手', '欧美'],
    referencePrompt: 'A young woman with distinctive style wearing oversized clothing, black or neon-colored hair, piercing blue eyes, edgy and cool appearance',
    avatarUrl: '🖤',
    hotness: 92,
  },
  {
    id: 'tom-cruise',
    name: 'Tom Cruise (汤姆·克鲁斯)',
    nameEn: 'Tom Cruise',
    category: 'hollywood',
    tags: ['演员', '好莱坞'],
    referencePrompt: 'A man with handsome face, short dark brown hair, intense blue eyes, athletic build, wearing a leather jacket or pilot jumpsuit, confident smirk',
    avatarUrl: '🛩️',
    hotness: 89,
  },
  {
    id: 'ryan-gosling',
    name: 'Ryan Gosling (瑞恩·高斯林)',
    nameEn: 'Ryan Gosling',
    category: 'hollywood',
    tags: ['演员', '好莱坞'],
    referencePrompt: 'A man with handsome clean-cut face, light brown hair, blue eyes, wearing a stylish casual outfit or sharp suit, charming smile',
    avatarUrl: '🎭',
    hotness: 90,
  },
  {
    id: 'zendaya',
    name: 'Zendaya (赞达亚)',
    nameEn: 'Zendaya',
    category: 'hollywood',
    tags: ['演员', '好莱坞'],
    referencePrompt: 'A young woman with stunning features, brown skin, often changing hairstyles, incredibly fashionable, wearing high-fashion red carpet outfit',
    avatarUrl: '✨',
    hotness: 93,
  },
  {
    id: 'margot-robbie',
    name: 'Margot Robbie (玛格特·罗比)',
    nameEn: 'Margot Robbie',
    category: 'hollywood',
    tags: ['演员', '好莱坞'],
    referencePrompt: 'A beautiful woman with blonde hair, blue eyes, Australian features, wearing glamorous outfit, confident and radiant smile',
    avatarUrl: '🦋',
    hotness: 91,
  },

  // ========== 音乐巨星 ==========
  {
    id: 'beyonce',
    name: 'Beyoncé (碧昂丝)',
    nameEn: 'Beyoncé',
    category: 'music',
    tags: ['歌手', '欧美'],
    referencePrompt: 'A stunning woman with honey-blonde hair flowing in waves, brown skin, powerful confident presence, wearing a dazzling stage performance outfit',
    avatarUrl: '👑',
    hotness: 97,
  },
  {
    id: 'drake',
    name: 'Drake (德雷克)',
    nameEn: 'Drake',
    category: 'music',
    tags: ['说唱', '欧美'],
    referencePrompt: 'A man with beard, short dark hair, often wearing a stylish casual outfit or designer streetwear, confident and relaxed expression',
    avatarUrl: '🦉',
    hotness: 88,
  },
  {
    id: 'eminem',
    name: 'Eminem (埃米纳姆)',
    nameEn: 'Eminem',
    category: 'music',
    tags: ['说唱', '欧美'],
    referencePrompt: 'A man with bleached blonde short hair, intense blue eyes, often wearing a hoodie or tank top, slim build, fierce expression',
    avatarUrl: '🎤',
    hotness: 86,
  },
  {
    id: 'dua-lipa',
    name: 'Dua Lipa (杜阿·利帕)',
    nameEn: 'Dua Lipa',
    category: 'music',
    tags: ['歌手', '欧美'],
    referencePrompt: 'A woman with long dark brown hair, distinctive British-Albanian features, glamorous makeup, wearing a stylish fashion-forward outfit',
    avatarUrl: '💃',
    hotness: 89,
  },

  // ========== 科技大佬 ==========
  {
    id: 'elon-musk',
    name: 'Elon Musk (埃隆·马斯克)',
    nameEn: 'Elon Musk',
    category: 'tech',
    tags: ['科技', 'CEO'],
    referencePrompt: 'A man of medium build with short light brown hair, distinctive jawline, often wearing a dark t-shirt or suit, confident expression',
    avatarUrl: '🚀',
    hotness: 98,
  },
  {
    id: 'mark-zuckerberg',
    name: '扎克伯格',
    nameEn: 'Mark Zuckerberg',
    category: 'tech',
    tags: ['科技', 'Meta'],
    referencePrompt: 'A man with short curly brown/blond hair, blue eyes, clean-shaven, often wearing a simple t-shirt or hoodie, youthful appearance',
    avatarUrl: '👤',
    hotness: 93,
  },
  {
    id: 'sundar-pichai',
    name: '桑达尔·皮查伊',
    nameEn: 'Sundar Pichai',
    category: 'tech',
    tags: ['科技', 'Google'],
    referencePrompt: 'An Indian-American man with short black hair, glasses, clean-shaven, warm professional smile, wearing a casual button-down shirt',
    avatarUrl: '🔍',
    hotness: 85,
  },
  {
    id: 'sam-altman',
    name: 'Sam Altman (山姆·奥特曼)',
    nameEn: 'Sam Altman',
    category: 'tech',
    tags: ['科技', 'OpenAI'],
    referencePrompt: 'A young man with short brown hair, clean-shaven, casual and approachable look, often wearing a simple t-shirt or sweater, thoughtful expression',
    avatarUrl: '🤖',
    hotness: 92,
  },

  // ========== 体育巨星 ==========
  {
    id: 'leo-messi',
    name: 'Messi (梅西)',
    nameEn: 'Lionel Messi',
    category: 'sports',
    tags: ['足球', '阿根廷'],
    referencePrompt: 'A relatively short man with beard, short dark hair, athletic build, wearing a blue and white striped football jersey or casual sportswear, South American appearance',
    avatarUrl: '⚽',
    hotness: 97,
  },
  {
    id: 'cristiano-ronaldo',
    name: 'C罗',
    nameEn: 'Cristiano Ronaldo',
    category: 'sports',
    tags: ['足球', '葡萄牙'],
    referencePrompt: 'A man with muscular athletic build, styled dark hair often gelled up, clean-shaven or light stubble, confident intense expression, wearing football jersey or tailored suit, Southern European appearance',
    avatarUrl: '🏆',
    hotness: 97,
  },
  {
    id: 'kobe-bryant',
    name: '科比',
    nameEn: 'Kobe Bryant',
    category: 'sports',
    tags: ['篮球', '湖人'],
    referencePrompt: 'A tall athletic man with bald head, intense focused expression, wearing a purple and gold Lakers jersey with number 24, basketball in hand',
    avatarUrl: '🏀',
    hotness: 95,
  },
  {
    id: 'lebron-james',
    name: 'LeBron James (勒布朗·詹姆斯)',
    nameEn: 'LeBron James',
    category: 'sports',
    tags: ['篮球', 'NBA'],
    referencePrompt: 'A tall powerful athletic man with bald head or very short hair, muscular build, wearing a basketball jersey or stylish suit, intense confident expression',
    avatarUrl: '👑',
    hotness: 93,
  },
  {
    id: 'michael-jordan',
    name: 'Michael Jordan (迈克尔·乔丹)',
    nameEn: 'Michael Jordan',
    category: 'sports',
    tags: ['篮球', 'NBA'],
    referencePrompt: 'A tall athletic man with bald head, distinctive goatee, wearing a red Chicago Bulls jersey with number 23 or a sharp suit, legendary presence',
    avatarUrl: '🐐',
    hotness: 96,
  },

  // ========== 动漫/虚拟角色 ==========
  {
    id: 'spider-man',
    name: 'Spider-Man (蜘蛛侠)',
    nameEn: 'Spider-Man',
    category: 'anime',
    tags: ['漫威', '超级英雄'],
    referencePrompt: 'A person wearing a full-body red and blue spider-man suit with web pattern and white eye lenses on the mask, athletic agile build, dynamic pose',
    avatarUrl: '🕷️',
    hotness: 96,
  },
  {
    id: 'iron-man',
    name: 'Iron Man (钢铁侠)',
    nameEn: 'Iron Man',
    category: 'anime',
    tags: ['漫威', '超级英雄'],
    referencePrompt: 'A person wearing a high-tech red and gold Iron Man suit with glowing arc reactor in chest, metallic armor plating, futuristic and powerful appearance',
    avatarUrl: '⚙️',
    hotness: 95,
  },
  {
    id: 'batman',
    name: 'Batman (蝙蝠侠)',
    nameEn: 'Batman',
    category: 'anime',
    tags: ['DC', '超级英雄'],
    referencePrompt: 'A person wearing a black Batman suit with dark cape and cowl, bat symbol on chest, muscular build, dark and mysterious atmosphere, Gotham city background',
    avatarUrl: '🦇',
    hotness: 93,
  },
  {
    id: 'goku',
    name: '孙悟空',
    nameEn: 'Goku (Dragon Ball)',
    category: 'anime',
    tags: ['动漫', '日漫'],
    referencePrompt: 'An anime-style man with spiky black hair pointing upward, wearing an orange and blue martial arts gi, muscular athletic build, energetic and cheerful expression, anime art style',
    avatarUrl: '🐉',
    hotness: 94,
  },
  {
    id: 'naruto',
    name: '鸣人',
    nameEn: 'Naruto Uzumaki',
    category: 'anime',
    tags: ['动漫', '日漫'],
    referencePrompt: 'An anime-style young man with spiky blonde hair, blue eyes, whisker marks on cheeks, wearing an orange and black ninja outfit, headband with metal plate, energetic smile, anime art style',
    avatarUrl: '🍥',
    hotness: 92,
  },
  {
    id: 'superman',
    name: 'Superman (超人)',
    nameEn: 'Superman',
    category: 'anime',
    tags: ['DC', '超级英雄'],
    referencePrompt: 'A person wearing a blue Superman suit with red cape, yellow S-shield on chest, red boots, muscular heroic build, standing heroically with confident expression',
    avatarUrl: '🦸',
    hotness: 91,
  },
  {
    id: 'pikachu',
    name: 'Pikachu (皮卡丘)',
    nameEn: 'Pikachu (Pokémon)',
    category: 'anime',
    tags: ['动漫', '宝可梦'],
    referencePrompt: 'A cute yellow Pikachu character with pointy ears with black tips, red cheeks, small mouth, lightning bolt shaped tail, adorable and cheerful, cartoon style',
    avatarUrl: '⚡',
    hotness: 90,
  },
  {
    id: 'deadpool',
    name: 'Deadpool (死侍)',
    nameEn: 'Deadpool',
    category: 'anime',
    tags: ['漫威', '反英雄'],
    referencePrompt: 'A person wearing a full-body red and black Deadpool suit with white eye patches on the mask, dual katana swords on back, humorous and chaotic vibe, breaking the fourth wall pose',
    avatarUrl: '💀',
    hotness: 93,
  },

  // ========== 政商领袖 ==========
  {
    id: 'trump',
    name: 'Trump (特朗普)',
    nameEn: 'Donald Trump',
    category: 'business',
    tags: ['政治', '美国'],
    referencePrompt: 'A man with distinctive blonde swept-back hair, squinting expression, wearing a dark navy suit with long red tie, confident posture, American flag pin on lapel',
    avatarUrl: '🇺🇸',
    hotness: 88,
  },
  {
    id: 'obama',
    name: 'Obama (奥巴马)',
    nameEn: 'Barack Obama',
    category: 'business',
    tags: ['政治', '美国'],
    referencePrompt: 'A tall man with short graying black hair, brown skin, warm intelligent smile, wearing a sharp dark suit with tie, distinguished and approachable presence',
    avatarUrl: '🇺🇸',
    hotness: 87,
  },
  {
    id: 'kim-jong-un',
    name: '金正恩',
    nameEn: 'Kim Jong-un',
    category: 'business',
    tags: ['政治', '朝鲜'],
    referencePrompt: 'A heavyset East Asian man with distinctive flat-top short black hair, clean-shaven round face, wearing a dark Mao-style button-up suit, stern but sometimes smiling expression',
    avatarUrl: '🇰🇵',
    hotness: 86,
  },
];

export const scenarios = [
  { id: 'red-carpet', label: '走红毯', emoji: '🏆', prompt: 'walking together on a glamorous red carpet event, paparazzi cameras flashing in background' },
  { id: 'coffee', label: '一起喝咖啡', emoji: '☕', prompt: 'sitting together at a cozy cafe, having coffee and a friendly conversation, warm lighting' },
  { id: 'selfie', label: '自拍合影', emoji: '🤳', prompt: 'taking a fun selfie together, both making a peace sign or smiling at camera, close-up shot, casual fun vibe' },
  { id: 'travel', label: '旅游打卡', emoji: '✈️', prompt: 'standing together at a famous tourist landmark, traveling together, scenic background' },
  { id: 'dinner', label: '共进晚餐', emoji: '🍽️', prompt: 'having dinner together at an elegant restaurant, candlelight, fine dining atmosphere' },
  { id: 'stage', label: '同台演出', emoji: '🎤', prompt: 'performing together on a massive concert stage, dramatic stage lighting, crowd cheering in background' },
  { id: 'sports', label: '一起运动', emoji: '💪', prompt: 'playing sports together on a professional field/court, athletic atmosphere, action shot' },
  { id: 'business', label: '商务会面', emoji: '🤝', prompt: 'shaking hands at a formal business meeting, modern office or conference room, professional atmosphere' },
];
